### PR TITLE
v2.8.0

### PR DESCRIPTION
**Pull request by conda-forge-linter**
This PR adds version 2.8.0, changes the release URL to github, and adds me as a maintiner.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge/depfinder This PR is ready for review!

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by CJ-Wright** [comment]
LGTM, thank you very much!

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Pull request merged**
